### ISSUE TITLE
Tag and update

### ISSUE THREAD

**Issue by kenayagi** [HSRNetwork/docker-powerdns-admin#1]
Would you consider tagging (with something like 2019.12.03) and update the image?

**Comment by PhilipSchmid** [comment]
Hi @kenayagi ,

Would be possible. Do you just mean the date at which the Docker image was built? Anything other would be challenging because we use directly `git clone` the https://github.com/ngoduykhanh/PowerDNS-Admin repository inside our `Dockerfile`. They do not release specific versions...

https://github.com/HSRNetwork/docker-powerdns-admin/blob/ee545604bfc3305cf36a240812c726c96b6821c8/Dockerfile#L7-L8

Thanks,

Regards,
Philip

**Comment by kenayagi** [comment]
Yes. I've seen on upstream that they don't release anything, so I thought that a simple date would _at least_ make the docker image trackable/reproducible.

**Comment by kenayagi** [comment]
Is the associated Docker Hub repo already setup for autobuild and tagging?
https://hub.docker.com/r/hsrnetwork/powerdns-admin/tags

**Comment by PhilipSchmid** [comment]
Yes it is. It just finished building the image. Docker Hub is super slow at the moment...

**Comment by kenayagi** [comment]
> Yes it is. It just finished building the image.

Great. Thank you! :thumbsup:
